import Link from "next/link";
import { PrintButton } from "@/components/PrintButton";
import { formatDatePKT } from "@/lib/attendance/format";
import { loadPayrollExportReport } from "@/lib/payroll/export-data";
import {
  filtersToSearchParams,
  parsePayrollExportFilters,
} from "@/lib/payroll/export-ui";
import type { PayrollExportGroupTotal, PayrollExportRow } from "@/lib/payroll/export";

type Search = Record<string, string | string[] | undefined>;

const PKR = new Intl.NumberFormat("en-PK", {
  style: "currency",
  currency: "PKR",
  maximumFractionDigits: 0,
});

function searchToParams(search: Search): URLSearchParams {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(search)) {
    if (Array.isArray(value)) {
      for (const item of value) params.append(key, item);
    } else if (value) {
      params.set(key, value);
    }
  }
  return params;
}

export default async function PayrollExportPage({
  searchParams,
}: {
  searchParams: Promise<Search>;
}) {
  const rawSearch = await searchParams;
  const filters = parsePayrollExportFilters(searchToParams(rawSearch));
  const { me, report, employees, branches, departments } =
    await loadPayrollExportReport(filters);
  const csvParams = filtersToSearchParams(filters).toString();
  const generatedAt = new Intl.DateTimeFormat("en-GB", {
    timeZone: "Asia/Karachi",
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date());

  return (
    <div className="space-y-6 print:bg-white">
      <style>{`
        @media print {
          @page { size: landscape; margin: 10mm; }
          body { background: white !important; }
          aside, header:not(.payroll-print-header), nav, .print\\:hidden { display: none !important; }
          main { overflow: visible !important; }
          .payroll-report { box-shadow: none !important; border: 0 !important; }
          table { page-break-inside: auto; }
          tr { page-break-inside: avoid; page-break-after: auto; }
        }
      `}</style>

      <section className="print:hidden">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold text-gray-900">Payroll Export Center</h1>
            <p className="text-sm text-gray-500">
              Generate payroll-ready printable and CSV reports. This does not mark
              salaries as paid.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Link
              href="/admin/payroll"
              className="rounded-md bg-white px-4 py-2 text-sm text-gray-600 ring-1 ring-inset ring-gray-200 hover:bg-gray-50"
            >
              Back to payroll preview
            </Link>
            <PrintButton />
            <Link
              href={`/admin/payroll/export/csv?${csvParams}`}
              className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500"
            >
              Download CSV
            </Link>
          </div>
        </div>
      </section>

      <FilterForm
        filters={filters}
        employees={employees}
        branches={branches}
        departments={departments}
      />

      <article className="payroll-report rounded-lg bg-white p-5 shadow ring-1 ring-black/5">
        <header className="payroll-print-header border-b border-gray-200 pb-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-gray-500">
            EN Consultants (Pvt) Ltd.
          </p>
          <h2 className="mt-1 text-xl font-semibold text-gray-900">
            Payroll Export / Salary Payable Report
          </h2>
          <dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4">
            <Info label="Period" value={report.periodLabel} />
            <Info label="Scope" value={report.scopeLabel} />
            <Info label="Generated by" value={me.appUser.display_name} />
            <Info label="Generated at" value={`${generatedAt} PKT`} />
          </dl>
        </header>

        <section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">
          <Stat label="Employees" value={report.totals.employeeCount} />
          <Stat label="Gross/base payable" value={PKR.format(report.totals.grossBasePayable)} />
          <Stat label="Deductions" value={PKR.format(report.totals.deductionAmount)} />
          <Stat label="Net payable" value={PKR.format(report.totals.netPayable)} />
        </section>

        <section className="mt-6 overflow-x-auto">
          <h3 className="text-sm font-semibold text-gray-700">Employee payroll rows</h3>
          <PayrollTable rows={report.rows} />
        </section>

        <section className="mt-6 grid gap-4 lg:grid-cols-2">
          <GroupTotals title="Branch-wise totals" rows={report.branchTotals} />
          <GroupTotals title="Department/category-wise totals" rows={report.departmentTotals} />
        </section>

        {report.monthlyBreakdown.length > 0 && (
          <section className="mt-6 overflow-x-auto">
            <h3 className="text-sm font-semibold text-gray-700">Monthly breakdown</h3>
            <table className="mt-3 min-w-full divide-y divide-gray-200 text-xs">
              <thead className="bg-gray-50">
                <tr>
                  <Th>Month</Th>
                  <Th>Name</Th>
                  <Th className="text-right">Gross</Th>
                  <Th className="text-right">Deduction</Th>
                  <Th className="text-right">Net</Th>
                  <Th className="text-right">Absent</Th>
                  <Th className="text-right">Late</Th>
                  <Th className="text-right">Half-day</Th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {report.monthlyBreakdown.map((row) => (
                  <tr key={`${row.employeeId}-${row.month}`}>
                    <Td>{row.month}</Td>
                    <Td>{row.employeeName}</Td>
                    <Td className="text-right tabular-nums">{PKR.format(row.grossBasePayable)}</Td>
                    <Td className="text-right tabular-nums">{PKR.format(row.deductionAmount)}</Td>
                    <Td className="text-right tabular-nums">{PKR.format(row.netPayable)}</Td>
                    <Td className="text-right tabular-nums">{row.absentDays}</Td>
                    <Td className="text-right tabular-nums">{row.lateCount}</Td>
                    <Td className="text-right tabular-nums">{row.halfDayCount}</Td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        <footer className="mt-6 border-t border-gray-200 pt-3 text-xs text-gray-500">
          This is a payroll-ready internal report generated by EN HRM.
        </footer>
      </article>
    </div>
  );
}

function FilterForm({
  filters,
  employees,
  branches,
  departments,
}: {
  filters: ReturnType<typeof parsePayrollExportFilters>;
  employees: Array<{ id: string; full_name: string; branch_code: string | null }>;
  branches: Array<{ id: string; name: string; code: string }>;
  departments: Array<{ id: string; name: string }>;
}) {
  return (
    <section className="rounded-lg bg-white p-4 shadow ring-1 ring-black/5 print:hidden">
      <form action="/admin/payroll/export" className="grid gap-3 md:grid-cols-4 xl:grid-cols-6">
        <Field label="Date mode">
          <select name="mode" defaultValue={filters.mode} className={INPUT_CLASS}>
            <option value="monthly">Monthly</option>
            <option value="custom_range">Custom range</option>
            <option value="yearly">Yearly</option>
          </select>
        </Field>
        <Field label="Month">
          <input name="month" type="month" defaultValue={filters.month} className={INPUT_CLASS} />
        </Field>
        <Field label="Year">
          <input name="year" type="number" min="2000" max="2100" defaultValue={filters.year} className={INPUT_CLASS} />
        </Field>
        <Field label="Start date">
          <input name="start_date" type="date" defaultValue={filters.startDate} className={INPUT_CLASS} />
        </Field>
        <Field label="End date">
          <input name="end_date" type="date" defaultValue={filters.endDate} className={INPUT_CLASS} />
        </Field>
        <Field label="Scope">
          <select name="scope" defaultValue={filters.scope} className={INPUT_CLASS}>
            <option value="all">All company</option>
            <option value="branch">Branch</option>
            <option value="department">Department/category</option>
            <option value="employee">Employee</option>
          </select>
        </Field>
        <Field label="Branch">
          <select name="branch_id" defaultValue={filters.branchId ?? ""} className={INPUT_CLASS}>
            <option value="">Any branch</option>
            {branches.map((branch) => (
              <option key={branch.id} value={branch.id}>{branch.name} ({branch.code})</option>
            ))}
          </select>
        </Field>
        <Field label="Department/category">
          <select name="department_id" defaultValue={filters.departmentId ?? ""} className={INPUT_CLASS}>
            <option value="">Any department</option>
            {departments.map((department) => (
              <option key={department.id} value={department.id}>{department.name}</option>
            ))}
          </select>
        </Field>
        <Field label="Employee">
          <select name="employee_id" defaultValue={filters.employeeId ?? ""} className={INPUT_CLASS}>
            <option value="">Any employee</option>
            {employees.map((employee) => (
              <option key={employee.id} value={employee.id}>
                {employee.full_name}{employee.branch_code ? ` · ${employee.branch_code}` : ""}
              </option>
            ))}
          </select>
        </Field>
        <div className="flex items-end">
          <button
            type="submit"
            className="w-full rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500"
          >
            Generate report
          </button>
        </div>
      </form>
    </section>
  );
}

function PayrollTable({ rows }: { rows: PayrollExportRow[] }) {
  return (
    <table className="mt-3 min-w-full divide-y divide-gray-200 text-xs">
      <thead className="bg-gray-50">
        <tr>
          <Th>Employee</Th>
          <Th>Contact email</Th>
          <Th>Contact number</Th>
          <Th>CNIC</Th>
          <Th>Bank</Th>
          <Th>Bank branch</Th>
          <Th>Account / IBAN</Th>
          <Th>Branch</Th>
          <Th>Department</Th>
          <Th>Role</Th>
          <Th className="text-right">Salary</Th>
          <Th>Period</Th>
          <Th className="text-right">Work days</Th>
          <Th className="text-right">Present</Th>
          <Th className="text-right">Remote</Th>
          <Th className="text-right">Leave</Th>
          <Th className="text-right">Holidays</Th>
          <Th className="text-right">Absent</Th>
          <Th className="text-right">Late</Th>
          <Th className="text-right">Late ded.</Th>
          <Th className="text-right">Half-day</Th>
          <Th className="text-right">Half ded.</Th>
          <Th className="text-right">Total ded.</Th>
          <Th className="text-right">Gross</Th>
          <Th className="text-right">Deduction</Th>
          <Th className="text-right">Net</Th>
          <Th>Notes</Th>
        </tr>
      </thead>
      <tbody className="divide-y divide-gray-100">
        {rows.map((row) => (
          <tr key={row.employeeId}>
            <Td className="font-medium text-gray-900">{row.employeeName}</Td>
            <Td>{row.contactEmail ?? "—"}</Td>
            <Td>{row.contactNumber ?? "—"}</Td>
            <Td>{row.cnic ?? "—"}</Td>
            <Td>{row.bankName ?? "—"}</Td>
            <Td>{row.bankBranchName ?? "—"}</Td>
            <Td>{row.bankAccountOrIban ?? "—"}</Td>
            <Td>{row.branchCode ?? row.branchName ?? "—"}</Td>
            <Td>{row.departmentName ?? "—"}</Td>
            <Td>{row.role}</Td>
            <Td className="text-right tabular-nums">{PKR.format(row.monthlySalary)}</Td>
            <Td>{formatPeriod(row.periodStart, row.periodEnd)}</Td>
            <Td className="text-right tabular-nums">{row.scheduledWorkingDays}</Td>
            <Td className="text-right tabular-nums">{row.presentDays}</Td>
            <Td className="text-right tabular-nums">{row.remoteDays}</Td>
            <Td className="text-right tabular-nums">{row.leaveDays}</Td>
            <Td className="text-right tabular-nums">{row.paidHolidays}</Td>
            <Td className="text-right tabular-nums">{row.absentDays}</Td>
            <Td className="text-right tabular-nums">{row.lateCount}</Td>
            <Td className="text-right tabular-nums">{row.lateDeductionDays}</Td>
            <Td className="text-right tabular-nums">{row.halfDayCount}</Td>
            <Td className="text-right tabular-nums">{row.halfDayDeductionDays.toFixed(1)}</Td>
            <Td className="text-right tabular-nums">{row.totalDeductionDays.toFixed(1)}</Td>
            <Td className="text-right tabular-nums">{PKR.format(row.grossBasePayable)}</Td>
            <Td className="text-right tabular-nums">{PKR.format(row.deductionAmount)}</Td>
            <Td className="text-right font-semibold tabular-nums text-green-700">
              {PKR.format(row.netPayable)}
            </Td>
            <Td>{row.notesStatus}</Td>
          </tr>
        ))}
        {rows.length === 0 && (
          <tr>
            <td colSpan={27} className="px-3 py-6 text-center text-sm text-gray-500">
              No employees match the selected export scope.
            </td>
          </tr>
        )}
      </tbody>
    </table>
  );
}

function GroupTotals({
  title,
  rows,
}: {
  title: string;
  rows: PayrollExportGroupTotal[];
}) {
  return (
    <section>
      <h3 className="text-sm font-semibold text-gray-700">{title}</h3>
      <table className="mt-3 min-w-full divide-y divide-gray-200 text-xs">
        <thead className="bg-gray-50">
          <tr>
            <Th>Name</Th>
            <Th className="text-right">Employees</Th>
            <Th className="text-right">Gross</Th>
            <Th className="text-right">Deduction</Th>
            <Th className="text-right">Net</Th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-100">
          {rows.map((row) => (
            <tr key={row.key}>
              <Td>{row.label}</Td>
              <Td className="text-right tabular-nums">{row.employeeCount}</Td>
              <Td className="text-right tabular-nums">{PKR.format(row.grossBasePayable)}</Td>
              <Td className="text-right tabular-nums">{PKR.format(row.deductionAmount)}</Td>
              <Td className="text-right tabular-nums">{PKR.format(row.netPayable)}</Td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}

function formatPeriod(start: string, end: string): string {
  return `${formatDatePKT(start)} - ${formatDatePKT(end)}`;
}

const INPUT_CLASS =
  "mt-1 block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block text-xs font-medium text-gray-700">
      {label}
      {children}
    </label>
  );
}

function Info({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs uppercase tracking-wide text-gray-500">{label}</dt>
      <dd className="mt-0.5 font-medium text-gray-900">{value}</dd>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="rounded-md border border-gray-200 bg-gray-50 px-4 py-3">
      <p className="text-xs uppercase tracking-wide text-gray-500">{label}</p>
      <p className="mt-1 text-lg font-semibold tabular-nums text-gray-900">{value}</p>
    </div>
  );
}

function Th({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <th className={`px-3 py-2 text-left text-[11px] font-semibold uppercase tracking-wide text-gray-500 ${className}`}>
      {children}
    </th>
  );
}

function Td({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <td className={`px-3 py-2 align-top text-gray-700 ${className}`}>{children}</td>;
}
